### ISSUE TITLE
use in blender

### ISSUE THREAD

**Issue by zjxcc** [elijah-atkins/ARKitBlendshapeHelper#1]
Hello, can you give me a detailed instruction, thank you.
I import an obj in blender, I don't know how to set 1-52 frame, and I get this error.
------
AttributeError: 'NoneType' object has no attribute 'select_set'
------

**Comment by Lipolan** [comment]
> Hello, have you resolved it? How to generate blendshapes?

**Comment by elijah-atkins** [comment]
To use Arkit Helper,  add a temporary facial rig on your obj model. You can create a facial rig with rigify "Human" meta-rig or Auto-rig Pro (a paid add-on that simplifies rigging).

Next, you need to pose your model according to the Arkit Face Blendshapes. ARKit Helper will show the name of the expected pose for frames 1-52. Frame 0 should be your default resting position with the mouth closed. You should keyframe each pose with constant interpolation. You can see examples of the poses here: [https://arkit-face-blendshapes.com/](https://arkit-face-blendshapes.com/). 

After keyframing all the poses, make a copy of the mesh. Set the original mesh as "Source" and the copy as "Target". Arkit Helper will generate Arkit-compatible shape keys for the Target mesh. You can test the shape keys and if you're not satisfied adjust the Keyframes, delete the duplicate, and repeat the process.

If the Target mesh is only the head, you can delete the original mesh and the temporary facial rig. Then, place the Target mesh in the right position, parent it to the original rig, and adjust the weights. If the Target mesh is the whole body, you may want to create a new body rig for it. I like the VRM rig from this addon [https://vrm-addon-for-blender.info/](https://vrm-addon-for-blender.info/)

**Comment by Treata11** [comment]
@elijah-atkins Is there a possibility that you share a working example of it or maybe showcase it in a video?
